### ISSUE TITLE
Can I collaborate for translate all application to spanish?

### ISSUE THREAD

**Issue by johnfelipe** [steedos-labs/contract#48]
I want to try this in Spanish for a research academy
I want to collaborate
Is possible?

**Comment by hotlong** [comment]
that‘s great! thanks.

steedos objects can translate by an i18n.yml file. you can see samples here: 

https://github.com/steedos/steedos-platform/blob/master/packages/standard-objects/space_users.object.yml
https://github.com/steedos/steedos-platform/blob/master/packages/standard-objects/space_users.zh-CN.i18n.yml
