### ISSUE TITLE
合同对象新增验证规则，新增记录与全局编辑是正常验证的，单个字段编辑时会报验证规则错误

### ISSUE THREAD

**Issue by 1113211631** [steedos-labs/contract#74]
我用在一台完全新的机器，新clone的项目， 同样会有这个问题，
版本： 1.23.26

操作步骤：
1.git clone 项目
2.安装依赖
3. 启动服务
4. 新增一个合同记录
5. 新增一个合同验证规则  公式： LEN(remark) < 5   提示备注不能少于5个字
6. 全局编辑之前加的合同记录， 把备注增加到5个字以上， 可以正常保存
7. 单个字段编辑会提示 备注不能少于5个字，  实际记录备注已经超过5个字了
8. 再新增一条合同记录，现象也是一样的，

**Comment by heguangzhi** [comment]
访问端口是多少 谢谢了！
